### Elementwise Operations

In [9]:
import numpy as np

a = np.array([1,2,3,4])
f = np.array([1.2, 2.3, 4.5, 5.6])

print(a+f)
print(a*f)
print(a/f)
print(a**f)
print(a*10)

[2.2 4.3 7.5 9.6]
[ 1.2  4.6 13.5 22.4]
[0.83333333 0.86956522 0.66666667 0.71428571]
[1.00000000e+00 4.92457765e+00 1.40296115e+02 2.35253423e+03]
[10 20 30 40]


### Universal Functions (ufuncs)

In [10]:
radian = np.array([0.5, 0.7, 0.8, 0.9])
degree = np.rad2deg(radian) # convert radians to the angle in degrees
# 1 radian is equal to (180/π) degrees, or approximately 57.2958 degrees.
# 1 degree is equal to (π/180) radians, or approximately 0.0174533 radians.
print(radian)
print(degree)
print(np.sin(radian))

[0.5 0.7 0.8 0.9]
[28.64788976 40.10704566 45.83662361 51.56620156]
[0.47942554 0.64421769 0.71735609 0.78332691]


### Multi-Dimensional arrays

In [11]:
a = np.array([
    [0,1,2,3],
    [10,11,12,13]
    ])
print(a.shape) # shape = (rows, columns)
print(a.size) # element count
print(a.ndim) # number of dimensions
# set / get elements
print(a[1,3]) # get the element at the 1st row and 3rd column
a[1,3] = 0 # set new value for it
print(a[1,3])

(2, 4)
8
2
13
0


### Slicing

In [12]:
a = np.array([10,11,12,13,14])
print(a[1:3])
print(a[1:-2])
print(a[-4:3])
# omitting indices
print(a[:3])
print(a[-2:])
print(a[::2]) # every other element

[11 12]
[11 12]
[11 12]
[10 11 12]
[13 14]
[10 12 14]


In [13]:
# multi-dimension slicing
a = np.array([
    [0,1,2,3,4],
    [10,11,12,13,14],
    [20,21,22,23,24],
    [30,31,32,33,34],
    [40,41,42,43,44]
])

print(a[0, 2:4]) # output the 0th row
print(a[3:, 3:]) # output from 3rd row to end and 3rd column to end
print(a[2::2,::2]) # strided are also possible

[2 3]
[[33 34]
 [43 44]]
[[20 22 24]
 [40 42 44]]


### Creating a array with fast way

In [14]:
a = np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [18]:
# how to extract a specific column value
print(a[::,1::2]) # extract the 1st column and 3rd column
print(a[-1,:]) # extract the 4th row
print(a[4]) # extract the last row
print(a[1::2,:-1:2]) # extract elements with skip

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]]
[20 21 22 23 24]
[20 21 22 23 24]
[[ 5  7]
 [15 17]]


In [25]:
# share the same address
a = np.array([1,2,3,4])
b = a[:2]
print(a)
print(b)
b[0] = -1
print(b)
print(a)

[1 2 3 4]
[1 2]
[-1  2]
[-1  2  3  4]


In [27]:
# insert an replace element with slices
a = np.array([1,2,3,4,5])
a[-2:] = [-1,-2]
print(a)
# replace element to a same scalar value
a[-2:] = 99
print(a)

[ 1  2  3 -1 -2]
[ 1  2  3 99 99]
