### Fancy Indexing

In [4]:
import numpy as np

a = np.arange(0,80,10)
print(a)

indices = [1,2,-1]
print(a[indices])
# this is also work with setting
a[indices] = 99
print(a)

[ 0 10 20 30 40 50 60 70]
[10 20 70]
[ 0 99 99 30 40 50 60 99]


In [6]:
# indexing with boolean
masks = np.array([0,0,0,1,1,0,0,0],dtype=bool)
print(a[masks])

[30 40]


In [8]:
test_bool = np.array([-1,-3,1,4,-6,9,3])
negative = test_bool < 0
print(negative)
print(test_bool[negative]) # extract all elements < 0

[ True  True False False  True False False]
[-1 -3 -6]


### Fancy Indexing in 2-D

In [19]:
a = np.arange(36).reshape(6,6)
print(a)
# extract the diagonal elements
print(a[[0,1,2,3,4,5],[0,1,2,3,4,5]])
# combining slice and fancy indexing
print(a[3:,[0,2,4]])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[ 0  7 14 21 28 35]
[[18 20 22]
 [24 26 28]
 [30 32 34]]


In [ ]:
# practice