### Fancy Indexing

In [2]:
import numpy as np

a = np.arange(0,80,10)
print(a)

indices = [1,2,-1]
print(a[indices])
# this is also work with setting
a[indices] = 99
print(a)

[ 0 10 20 30 40 50 60 70]
[10 20 70]
[ 0 99 99 30 40 50 60 99]


In [6]:
# indexing with boolean
masks = np.array([0,0,0,1,1,0,0,0],dtype=bool)
print(a[masks])

[30 40]


In [8]:
test_bool = np.array([-1,-3,1,4,-6,9,3])
negative = test_bool < 0
print(negative)
print(test_bool[negative]) # extract all elements < 0

[ True  True False False  True False False]
[-1 -3 -6]


### Fancy Indexing in 2-D

In [19]:
a = np.arange(36).reshape(6,6)
print(a)
# extract the diagonal elements
print(a[[0,1,2,3,4,5],[0,1,2,3,4,5]])
# combining slice and fancy indexing
print(a[3:,[0,2,4]])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[ 0  7 14 21 28 35]
[[18 20 22]
 [24 26 28]
 [30 32 34]]


In [16]:
# practice
# 1. extract the elements indicated blue
# 2. Given 5 by 5 matrix from 0 to 24, extract all the elements in the matrix that divisible by 3 using a boolean mask.
a = np.arange(25).reshape(5,5)
print(a)
print(a[[0,2,3,3],[2,3,1,4]])
mask_1 = np.array([i%3==0 for i in range(25)]).reshape(5,5)
# above way of creating mask is cumbersome, below is a wiser way
mask_2 = a%3 == 0
print(a[mask_2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 2 13 16 19]
[ 0  3  6  9 12 15 18 21 24]


### Computations with arrays
1. Operations between multiple array objects are first checked for proper shape match.
2. Mathematical operators (+ - * / log...) apply element by element, on the values.
3. Reduction operation (mean std skew kurt sum...) apply to the whole array, unless an axis is specified.
4. Missing values propagate unless explicitly ignored (nanmean)

In [15]:
a = np.array([1,2,3,5,5,-3,-1])
print(a==a.max())
print(a>0) # logical operation element by element
b = a<0
print(a[b]) 

[False False False  True  True False False]
[ True  True  True  True  True False False]
[-3 -1]


#### The axis concept (indexing of sharp)
* In 1-D array, there is only one axis (axis = 0)
* In 2-D array, there are two axis (axis = 0, axis=1/-1)
  * 0 axis,it runs downward down the rows(from top to bottom)
  * 1 axis, it runs horizontally across the columns(from left to right)

In [7]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.sum()) # whole numbers
print(a.sum(axis=0)) # the sum of each columns (axis=-2 is the same with axis=0)
print(a.sum(axis=1)) # the sum of each rows (axis=-1 is the same with axis=1)

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]


In [46]:
# function combine with axis
a = np.array([[2,3],[0,1]])
print(a)
print(a.min()) # the min value among whole elements
print(a.min(axis=0)) # the min row
print(a.max(axis=-1)) # the max column

[[2 3]
 [0 1]]
0
[0 1]
[3 1]


array([2, 3])

In [51]:
# to understand the concept of argmax(), return the index(indices) of the maximum value in the array.
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.argmax(a, axis=0)) # find the max values for each columns and return its indices
print(np.argmin(a, axis=-1)) # find the min values for each rows
print(a.argmax()) # return the index along the flattened array

[1 1 1]
[0 0]
5


### Flattened indices and coordinate indices

In [59]:
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.flatten()) # convert the 3*3 matrix in to array.

# unravel_index is a function in the numpy module, can't be called on a numpy array instance.
max_index_flat = a.argmax() # get the index of the max value in flattened array
max_index_2d = np.unravel_index(max_index_flat, a.shape) # convert this flat index to a 2D index
print(max_index_flat)
print(max_index_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
8
(2, 2)


### Find positions of elements that satisfying demands

'where' for providing coordinates from mask

In [6]:
a = np.arange(-2,2)**2 # squares each element
print(a)
mask = a%2==0
print(mask)
print(np.where(mask)) # coordinates are returned as a tuple of arrays, one for each axis

[4 1 0 1]
[ True False  True False]
(array([0, 2]),)


In [27]:
a = np.arange(25).reshape(5,5)
print(a)
mask = a%3==0
print(mask)
print(np.where(mask))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]
 [False  True False False  True]]
(array([0, 0, 1, 1, 2, 3, 3, 4, 4]), array([0, 3, 1, 4, 2, 0, 3, 1, 4]))


'where' for constructing a new array by choosing values from other arrays of the same shape


In [32]:
positives = np.arange(4)
negatives = -positives
mask = np.array([True, False, True, False])
print(positives)
print(negatives)
print(np.where(mask, positives, negatives))

[0 1 2 3]
[ 0 -1 -2 -3]
[ 0 -1  2 -3]


In [33]:
# scalar values.
print(np.where(mask, 1, 0))

[1 0 1 0]


In [34]:
# both (other arrays and scalar values)
print(np.where(mask, positives, 0))

[0 0 2 0]
