## Exercise - wind statistics

1. Use the 'loadtxt' function from numpy to read the data into an array.

In [2]:
from numpy import loadtxt
import numpy as np 

data = loadtxt('wind_statistics/wind.data')

In [3]:
print(type(data))
print(data[:3, :]) # the first 3 rows
print(data[0, :]) # the first row for whole columns
print(data[:, :3]) # the first 3 columns for whole rows
print(data.shape) # to check how many rows and columns

<class 'numpy.ndarray'>
[[61.    1.    1.   15.04 14.96 13.17  9.29 13.96  9.87 13.67 10.25 10.83
  12.58 18.5  15.04]
 [61.    1.    2.   14.71 16.88 10.83  6.5  12.62  7.67 11.5  10.04  9.79
   9.67 17.54 13.83]
 [61.    1.    3.   18.5  16.88 12.33 10.13 11.17  6.17 11.25  8.04  8.5
   7.67 12.75 12.71]]
[61.    1.    1.   15.04 14.96 13.17  9.29 13.96  9.87 13.67 10.25 10.83
 12.58 18.5  15.04]
[[61.  1.  1.]
 [61.  1.  2.]
 [61.  1.  3.]
 ...
 [78. 12. 29.]
 [78. 12. 30.]
 [78. 12. 31.]]
(6574, 15)


2. The min, max and mean wind speeds and standard deviation of the wind speeds over all the locations and all the times

In [4]:
date_set = data[:, :3] # extract the first 3 columns
wind_set = data[:, 3:] # extract the 4th to end columns
print(date_set)
print(wind_set)
print(wind_set.min()) # find the min value from whole data set
print(wind_set.max()) # find the max value from whole data set
print(wind_set.mean()) # calculate the mean value
print(wind_set.std()) # standard deviation

[[61.  1.  1.]
 [61.  1.  2.]
 [61.  1.  3.]
 ...
 [78. 12. 29.]
 [78. 12. 30.]
 [78. 12. 31.]]
[[15.04 14.96 13.17 ... 12.58 18.5  15.04]
 [14.71 16.88 10.83 ...  9.67 17.54 13.83]
 [18.5  16.88 12.33 ...  7.67 12.75 12.71]
 ...
 [14.   10.29 14.42 ... 16.42 18.88 29.58]
 [18.5  14.04 21.29 ... 12.12 14.67 28.79]
 [20.33 17.41 27.29 ... 11.38 12.08 22.08]]
0.0
42.54
10.22837377040868
5.603840181095793


3. The min, max and mean wind speeds and standard deviation of the wind speeds at each location over all the times

In [5]:
# calculate the min max ... for each column.
min_lis = []
max_lis = []
mean_lis = []
std_lis = []
for i in range(wind_set.shape[1]):
    min_lis.append(wind_set[:, i].min())
    max_lis.append(wind_set[:, i].max())
    mean_lis.append(round(wind_set[:, i].mean(),2))
    std_lis.append(round(wind_set[:, i].std(),2))

print(np.array(min_lis))
print(np.array(max_lis))
print(np.array(mean_lis))
print(np.array(std_lis))


[0.67 0.21 1.5  0.   0.13 0.   0.   0.   0.   0.04 0.13 0.67]
[35.8  33.37 33.84 28.46 37.54 26.16 30.37 31.08 25.88 28.21 42.38 42.54]
[12.36 10.65 11.66  6.31 10.46  7.09  9.8   8.49  8.5   8.71 13.12 15.6 ]
[5.62 5.27 5.01 3.61 4.94 3.97 4.98 4.5  4.17 4.5  5.83 6.7 ]


4. The min, max...of the wind speeds across all the locations at each day (a different set of numbers for each day)

In [6]:
# calculate the min, max for each row.
min_lis_day = []
max_lis_day = []
mean_lis_day = []
std_lis_day = []
for i in range(wind_set.shape[0]):
    min_lis_day.append(wind_set[i, :].min())
    max_lis_day.append(wind_set[i, :].max())
    mean_lis_day.append(round(wind_set[i, :].mean(),2))
    std_lis_day.append(round(wind_set[i, :].std(),2))
    
print(np.array(min_lis_day))
print(np.array(max_lis_day))
print(np.array(mean_lis_day))
print(np.array(std_lis_day))


[9.29 6.5  6.17 ... 8.71 9.13 9.59]
[18.5  17.54 18.5  ... 29.58 28.79 27.29]
[13.1  11.8  11.34 ... 14.89 15.37 15.4 ]
[2.58 3.29 3.51 ... 5.51 5.3  5.46]


5. The location which has the greatest wind speed on each day (an integer column number for each day).

In [7]:
mask = wind_set[0,:] == wind_set[0,:].max()
print(mask)
print(np.where(mask))

[False False False False False False False False False False  True False]
(array([10]),)


6. Find the year, month and day on which the greatest windspeed was recorded.

In [8]:
greatest_val = wind_set.max()
print(greatest_val)
mask = wind_set == greatest_val
max_loc = np.where(mask)
print(max_loc)
# find the row in the corresponding dataset
print(date_set[max_loc[0],:])

42.54
(array([2161]), array([11]))
[[66. 12.  2.]]


7. Find the average wind speed in January for each location.

In [9]:
mask = date_set[:, 1] == 1
print(mask.size)
# the average wind speed in January for the 1st location.
print(wind_set[mask,0].mean())

6574
14.869551971326164


### Again, without any for loop

3. min, max .. at each location over all the days

In [10]:
print(wind_set.min(axis=0)) # axis=0 apply the calculation column-wise
print(wind_set.max(axis=0))
print(np.round(wind_set.mean(axis=0),2))
print(np.round(wind_set.std(axis=0),2))

#[0.67 0.21 1.5  0.   0.13 0.   0.   0.   0.   0.04 0.13 0.67]
#[35.8  33.37 33.84 28.46 37.54 26.16 30.37 31.08 25.88 28.21 42.38 42.54]
#[12.36 10.65 11.66  6.31 10.46  7.09  9.8   8.49  8.5   8.71 13.12 15.6 ]
#[5.62 5.27 5.01 3.61 4.94 3.97 4.98 4.5  4.17 4.5  5.83 6.7 ]

[0.67 0.21 1.5  0.   0.13 0.   0.   0.   0.   0.04 0.13 0.67]
[35.8  33.37 33.84 28.46 37.54 26.16 30.37 31.08 25.88 28.21 42.38 42.54]
[12.36 10.65 11.66  6.31 10.46  7.09  9.8   8.49  8.5   8.71 13.12 15.6 ]
[5.62 5.27 5.01 3.61 4.94 3.97 4.98 4.5  4.17 4.5  5.83 6.7 ]


4. min, max and mean across all the locations at each day

In [11]:
print(wind_set.min(axis=1))
print(wind_set.max(axis=1))
print(np.round(wind_set.mean(axis=1),2))
print(np.round(wind_set.std(axis=1),2))
#[9.29 6.5  6.17 ... 8.71 9.13 9.59]
#[18.5  17.54 18.5  ... 29.58 28.79 27.29]
#[13.1  11.8  11.34 ... 14.89 15.37 15.4 ]
#[2.58 3.29 3.51 ... 5.51 5.3  5.46]

[9.29 6.5  6.17 ... 8.71 9.13 9.59]
[18.5  17.54 18.5  ... 29.58 28.79 27.29]
[13.1  11.8  11.34 ... 14.89 15.37 15.4 ]
[2.58 3.29 3.51 ... 5.51 5.3  5.46]


5. find the location which has the greatest wind speed on each day

In [12]:
print(wind_set.argmax(axis=1))

[10 10  0 ... 11 11  2]


6. find the year, month and day on which the greatest wind speed was recorded.

In [13]:
# convert a flat index into a tuple of coordinate arrays.
max_row = np.unravel_index(wind_set.argmax(),wind_set.shape)[0]
print(max_row)
print(date_set[max_row,:])

# using where to solve this quiz (return tuple of arrays)
print(np.where(wind_set == wind_set.max()))

# other way for this quiz
# find the all max value thro row-wise, and argmax() the max row
print(wind_set.max(axis=1).argmax())

a = np.array([
    [ 20,  1,  2,  13,  4],
    [ 15,  6,  7,  8,  9],
    [1, 11, 12, 13, 14],
    [5, 16, 7, 18, 9],
    [2, 14, 2, 3, 16]
    ])
#print(a.max(axis=0)) # axis=0 is column-wise

2161
[66. 12.  2.]
(array([2161]), array([11]))
2161


7. find the average wind speed in Jan for each location.

In [14]:
januaries = date_set[:, 1]==1
wind_set[januaries].mean(axis=0)

array([14.86955197, 12.92166667, 13.29962366,  7.19949821, 11.67571685,
        8.05483871, 11.81935484,  9.5094086 ,  9.54320789, 10.05356631,
       14.55051971, 18.02876344])

### Bonus

1. the mean wind speed for each month in the dataset. Treat Jan 1961 and Jan 1962 as *different* months. (hint: first find a way to create an identifier unique for each month. The second step might require a for loop.)

In [32]:
whole_mean = []
for year in range(61,77):
    month_mean = []
    for i in range(1,13):
        mask = (date_set[:,0]==year) & (date_set[:,1]==i)
        month_mean.append(np.round(wind_set[mask].mean(),2))
    whole_mean.append(month_mean)

print(np.array(whole_mean))

[[11.38 13.49 11.07  8.41  8.97  9.7   9.02 10.79  9.99 11.48  8.97 10.84]
 [12.13 13.6   9.18 10.12 10.24 10.38  8.55 10.16  9.03  8.77  8.7  13.5 ]
 [11.4  12.2  12.23 11.67 11.92  9.58  7.98 10.63  9.61 11.99 12.02 11.7 ]
 [10.55 12.31 11.08 10.82 12.16 10.2   9.77  8.75  9.92  9.43 10.83 11.84]
 [13.21  7.79 11.99 11.74 10.03  9.6   8.48 10.35  9.5   9.66 12.39 11.66]
 [12.23 14.24 12.12 13.88 10.78  8.57  9.39  8.2   8.61  8.8  11.61 14.09]
 [10.57 13.12 14.87 11.01 10.92  8.2   9.32  8.75 10.46 13.59  9.88 11.07]
 [11.73  8.88 12.25 10.32  8.71  7.8   6.36  7.79 10.02 10.45 12.45 10.26]
 [10.5  11.19  9.38  9.84  7.6   7.97  9.08  8.89  8.08 10.34 10.64 10.57]
 [10.47 11.73 11.99 11.42  9.86  8.3  10.42  7.73 10.37 11.62 10.94  9.88]
 [11.17  9.4   9.13  7.81  8.42  8.86  6.6   7.66  6.78 11.04 11.18 11.67]
 [10.8  10.66 10.17 10.81 12.02  9.93  6.95  7.61  6.79  9.01 10.13 12.94]
 [10.01 11.46  9.67 11.26 10.41  8.76  7.61  7.42  8.96  8.64  9.73 10.97]
 [16.25 10.52  9.58  7.19

2. the min, max, mean and std of the wind speeds across all locations for each week (assume that the first week starts on Jan 1 1961) for the first 52 weeks. This can be done without any for loop.

In [54]:
# find out the first week
first_week_min = wind_set[:7, :].min()
print(first_week_min)
print(np.where(wind_set[:7, :]==first_week_min))
wind_set[:7, :].mean()


1.79
(array([3]), array([7]))


10.30154761904762

In [66]:
# Do it wisely, to reshape the array that extract from original data set.
weekly_data = wind_set[:52*7].reshape(-1,7*12)
# -1 in reshape allows numpy to calculate the correct number of rows \
# based on the original size of the array and the specified number of \
# columns.
print(weekly_data.shape)
print(weekly_data.min(axis=1))
print(weekly_data.max(axis=1))
print(np.round(weekly_data.mean(axis=1),2))
print(np.round(weekly_data.std(axis=1),2))

(52, 84)
[1.79 0.5  1.04 2.17 3.63 8.08 3.42 2.21 5.66 1.71 2.75 2.58 1.46 3.21
 1.54 0.83 1.38 3.83 1.04 3.33 1.63 3.29 3.21 1.58 2.88 4.42 3.54 2.67
 1.46 2.17 2.25 2.5  6.83 3.96 1.13 1.25 4.17 1.46 3.21 1.04 2.96 3.75
 2.21 1.71 1.33 0.63 2.88 1.92 3.13 5.46 0.58 0.42]
[18.5  20.71 20.79 27.63 27.71 26.38 28.62 29.63 25.8  22.71 22.95 21.54
 22.5  18.29 16.17 21.09 17.5  28.08 26.63 15.96 20.96 17.96 19.83 25.25
 24.71 21.87 21.29 22.5  21.42 25.37 20.25 14.58 24.3  22.29 24.71 20.25
 33.09 20.96 23.21 19.62 21.04 33.45 30.88 23.58 20.41 32.71 22.58 23.75
 29.33 25.62 24.41 29.33]
[10.3   8.89  9.3  14.92 12.79 16.04 13.69 11.76 13.06 10.08 12.75  9.8
 11.28  8.76  7.66  9.46  7.73 11.67  9.5   7.81  7.19  9.    8.88  9.1
 10.33 10.01 10.6  11.    6.5   8.99  9.41  7.8  12.43 11.87  9.45  8.19
 14.28  7.47 11.57  7.62 10.18 14.21 14.6  10.64  7.73  8.01  8.87  9.48
 11.86 14.06  8.66 10.35]
[3.6  4.63 4.8  5.47 5.66 4.11 4.55 4.94 4.67 4.02 4.46 3.92 4.27 3.57
 3.33 4.89 3.65 4.57 

### Bonus Bonus

Calculate the mean wind speed for each month without using a for loop. (hint: look at 'searchsored' and 'add.reduceat')

In [68]:
wind_set[:3, :]
date_set[:3, :]

array([[61.,  1.,  1.],
       [61.,  1.,  2.],
       [61.,  1.,  3.]])

In [84]:
mask = (date_set[:,1] == 1) & (date_set[:, 0] == 61)
print(wind_set[mask][:3,:])
summ = 0
for i in wind_set[mask].flatten():
    summ += i
print(summ/(31*12))

wind_set[mask].mean()

[[15.04 14.96 13.17  9.29 13.96  9.87 13.67 10.25 10.83 12.58 18.5  15.04]
 [14.71 16.88 10.83  6.5  12.62  7.67 11.5  10.04  9.79  9.67 17.54 13.83]
 [18.5  16.88 12.33 10.13 11.17  6.17 11.25  8.04  8.5   7.67 12.75 12.71]]
11.380645161290321


11.380645161290323