## Exercise - wind statistics

1. Use the 'loadtxt' function from numpy to read the data into an array.

In [3]:
from numpy import loadtxt
import numpy as np 

data = loadtxt('wind_statistics/wind.data')

In [4]:
print(type(data))
print(data[:3, :]) # the first 3 rows
print(data[0, :]) # the first row for whole columns
print(data[:, :3]) # the first 3 columns for whole rows
print(data.shape) # to check how many rows and columns

<class 'numpy.ndarray'>
[[61.    1.    1.   15.04 14.96 13.17  9.29 13.96  9.87 13.67 10.25 10.83
  12.58 18.5  15.04]
 [61.    1.    2.   14.71 16.88 10.83  6.5  12.62  7.67 11.5  10.04  9.79
   9.67 17.54 13.83]
 [61.    1.    3.   18.5  16.88 12.33 10.13 11.17  6.17 11.25  8.04  8.5
   7.67 12.75 12.71]]
[61.    1.    1.   15.04 14.96 13.17  9.29 13.96  9.87 13.67 10.25 10.83
 12.58 18.5  15.04]
[[61.  1.  1.]
 [61.  1.  2.]
 [61.  1.  3.]
 ...
 [78. 12. 29.]
 [78. 12. 30.]
 [78. 12. 31.]]
(6574, 15)


2. The min, max and mean wind speeds and standard deviation of the wind speeds over all the locations and all the times

In [5]:
date_set = data[:, :3] # extract the first 3 columns
wind_set = data[:, 3:] # extract the 4th to end columns
print(date_set)
print(wind_set)
print(wind_set.min()) # find the min value from whole data set
print(wind_set.max()) # find the max value from whole data set
print(wind_set.mean()) # calculate the mean value
print(wind_set.std()) # standard deviation

[[61.  1.  1.]
 [61.  1.  2.]
 [61.  1.  3.]
 ...
 [78. 12. 29.]
 [78. 12. 30.]
 [78. 12. 31.]]
[[15.04 14.96 13.17 ... 12.58 18.5  15.04]
 [14.71 16.88 10.83 ...  9.67 17.54 13.83]
 [18.5  16.88 12.33 ...  7.67 12.75 12.71]
 ...
 [14.   10.29 14.42 ... 16.42 18.88 29.58]
 [18.5  14.04 21.29 ... 12.12 14.67 28.79]
 [20.33 17.41 27.29 ... 11.38 12.08 22.08]]
0.0
42.54
10.22837377040868
5.603840181095793


3. The min, max and mean wind speeds and standard deviation of the wind speeds at each location over all the times

In [6]:
# calculate the min max ... for each column.
min_lis = []
max_lis = []
mean_lis = []
std_lis = []
for i in range(wind_set.shape[1]):
    min_lis.append(wind_set[:, i].min())
    max_lis.append(wind_set[:, i].max())
    mean_lis.append(round(wind_set[:, i].mean(),2))
    std_lis.append(round(wind_set[:, i].std(),2))

print(np.array(min_lis))
print(np.array(max_lis))
print(np.array(mean_lis))
print(np.array(std_lis))


[0.67 0.21 1.5  0.   0.13 0.   0.   0.   0.   0.04 0.13 0.67]
[35.8  33.37 33.84 28.46 37.54 26.16 30.37 31.08 25.88 28.21 42.38 42.54]
[12.36 10.65 11.66  6.31 10.46  7.09  9.8   8.49  8.5   8.71 13.12 15.6 ]
[5.62 5.27 5.01 3.61 4.94 3.97 4.98 4.5  4.17 4.5  5.83 6.7 ]


4. The min, max...of the wind speeds across all the locations at each day (a different set of numbers for each day)

In [7]:
# calculate the min, max for each row.
min_lis_day = []
max_lis_day = []
mean_lis_day = []
std_lis_day = []
for i in range(wind_set.shape[0]):
    min_lis_day.append(wind_set[i, :].min())
    max_lis_day.append(wind_set[i, :].max())
    mean_lis_day.append(round(wind_set[i, :].mean(),2))
    std_lis_day.append(round(wind_set[i, :].std(),2))
    
print(np.array(min_lis_day))
print(np.array(max_lis_day))
print(np.array(mean_lis_day))
print(np.array(std_lis_day))


[9.29 6.5  6.17 ... 8.71 9.13 9.59]
[18.5  17.54 18.5  ... 29.58 28.79 27.29]
[13.1  11.8  11.34 ... 14.89 15.37 15.4 ]
[2.58 3.29 3.51 ... 5.51 5.3  5.46]


5. The location which has the greatest wind speed on each day (an integer column number for each day).

In [8]:
mask = wind_set[0,:] == wind_set[0,:].max()
print(mask)
print(np.where(mask))

[False False False False False False False False False False  True False]
(array([10]),)


6. Find the year, month and day on which the greatest windspeed was recorded.

In [19]:
greatest_val = wind_set.max()
print(greatest_val)
mask = wind_set == greatest_val
max_loc = np.where(mask)
print(max_loc)
# find the row in the corresponding dataset
print(date_set[max_loc[0],:])

42.54
(array([2161]), array([11]))
[[66. 12.  2.]]


7. Find the average wind speed in January for each location.

In [79]:
mask = date_set[:, 1] == 1
print(mask.size)
# the average wind speed in January for the 1st location.
print(wind_set[mask,0].mean())

6574
14.869551971326164


### Again, without any for loop

3. min, max .. at each location over all the days

In [43]:
print(wind_set.min(axis=0)) # axis=0 apply the calculation column-wise
print(wind_set.max(axis=0))
print(np.round(wind_set.mean(axis=0),2))
print(np.round(wind_set.std(axis=0),2))

#[0.67 0.21 1.5  0.   0.13 0.   0.   0.   0.   0.04 0.13 0.67]
#[35.8  33.37 33.84 28.46 37.54 26.16 30.37 31.08 25.88 28.21 42.38 42.54]
#[12.36 10.65 11.66  6.31 10.46  7.09  9.8   8.49  8.5   8.71 13.12 15.6 ]
#[5.62 5.27 5.01 3.61 4.94 3.97 4.98 4.5  4.17 4.5  5.83 6.7 ]

[0.67 0.21 1.5  0.   0.13 0.   0.   0.   0.   0.04 0.13 0.67]
[35.8  33.37 33.84 28.46 37.54 26.16 30.37 31.08 25.88 28.21 42.38 42.54]
[12.36 10.65 11.66  6.31 10.46  7.09  9.8   8.49  8.5   8.71 13.12 15.6 ]
[5.62 5.27 5.01 3.61 4.94 3.97 4.98 4.5  4.17 4.5  5.83 6.7 ]


4. min, max and mean across all the locations at each day

In [52]:
print(wind_set.min(axis=1))
print(wind_set.max(axis=1))
print(np.round(wind_set.mean(axis=1),2))
print(np.round(wind_set.std(axis=1),2))
#[9.29 6.5  6.17 ... 8.71 9.13 9.59]
#[18.5  17.54 18.5  ... 29.58 28.79 27.29]
#[13.1  11.8  11.34 ... 14.89 15.37 15.4 ]
#[2.58 3.29 3.51 ... 5.51 5.3  5.46]

[9.29 6.5  6.17 ... 8.71 9.13 9.59]
[18.5  17.54 18.5  ... 29.58 28.79 27.29]
[13.1  11.8  11.34 ... 14.89 15.37 15.4 ]
[2.58 3.29 3.51 ... 5.51 5.3  5.46]


5. find the location which has the greatest wind speed on each day

In [54]:
print(wind_set.argmax(axis=1))

[10 10  0 ... 11 11  2]


6. find the year, month and day on which the greatest wind speed was recorded.

In [78]:
# convert a flat index into a tuple of coordinate arrays.
max_row = np.unravel_index(wind_set.argmax(),wind_set.shape)[0]
print(max_row)
print(date_set[max_row,:])

# using where to solve this quiz (return tuple of arrays)
print(np.where(wind_set == wind_set.max()))

# other way for this quiz
# find the all max value thro row-wise, and argmax() the max row
print(wind_set.max(axis=1).argmax())

a = np.array([
    [ 20,  1,  2,  13,  4],
    [ 15,  6,  7,  8,  9],
    [1, 11, 12, 13, 14],
    [5, 16, 7, 18, 9],
    [2, 14, 2, 3, 16]
    ])
#print(a.max(axis=0)) # axis=0 is column-wise

2161
[66. 12.  2.]
(array([2161]), array([11]))
2161
[20 16 12 18 16]


7. find the average wind speed in Jan for each location.

In [80]:
januaries = date_set[:, 1]==1
wind_set[januaries].mean(axis=0)

array([14.86955197, 12.92166667, 13.29962366,  7.19949821, 11.67571685,
        8.05483871, 11.81935484,  9.5094086 ,  9.54320789, 10.05356631,
       14.55051971, 18.02876344])