# Vector and Matrix Initializations

## basic initializations of vector and matrix

In [34]:
# Vectors
import numpy as np

a_3 = np.array([1, 2, 3]) # three elements along one axis.
a_3row = np.array([[1],[2],[3]]) # three elements along three axis
print(a_3.ndim, a_3.shape, a_3)
print(a_3row.ndim, a_3row.shape, a_3row)


a_12 = np.arange(12)
print(a_12.shape, a_12)
# arange used to generate a sequence of numbers with a specified range with array type

b_1_12 = a_12.reshape(1, 12)
print(b_1_12.shape, b_1_12)
# reshape the array into a 1 x 12 matrix

b_12_1 = a_12.reshape(12, 1)
print(b_12_1.shape, b_12_1)
# reshape the array into a 12 x 1 matrix

1 (3,) [1 2 3]
2 (3, 1) [[1]
 [2]
 [3]]
(12,) [ 0  1  2  3  4  5  6  7  8  9 10 11]
(1, 12) [[ 0  1  2  3  4  5  6  7  8  9 10 11]]
(12, 1) [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [17]:
# matrix
matri_2_2 = np.array([[1, 2, 3], [4, 5, 6]])
print(matri_2_2.shape,'\n', matri_2_2)

matri_3_5 = np.arange(12).reshape(3, 4)
print(matri_3_5.shape,'\n', matri_3_5)

(2, 3) 
 [[1 2 3]
 [4 5 6]]
(3, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## further methods for initialisations

In [9]:
vector_zero_1d = np.zeros(5)
print(vector_zero_1d)

vector_zero_3d = np.zeros((3,2))
print(vector_zero_3d)
print(vector_zero_3d.dtype)

vector_zero_2d = np.zeros((2,2), dtype=int)
print(vector_zero_2d)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64
[[0 0]
 [0 0]]


#### to generate a random matrix

In [10]:
matri_rand = np.random.rand(3,3)
print(matri_rand)

[[0.51595049 0.89804999 0.42366608]
 [0.10410122 0.71099422 0.38992314]
 [0.94615884 0.77461648 0.58062119]]


In [14]:
a = np.arange(5)
print(a)
b = np.diag(a) # diagonalize 1D values into diagonal matrix with other elements are all 0s
print(b)
c = np.diag(b) # if the input is already a diagonal matrix, it extracts the diagonal elements into 1D array
print(c)

[0 1 2 3 4]
[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]
[0 1 2 3 4]


In [17]:
b = np.eye(3, dtype=int) # to generate an identity matrix
print(b)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Multiplication, Transpose and Inverse

In [38]:

matri_3_3 = np.arange(1,7).reshape(3,2)
print(matri_3_3)
print(matri_3_3.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [45]:
print(np.multiply(matri_3_3, matri_3_3.T))
print(matri_3_3 * matri_3_3.T)
# scalar multiplication support
# matrix (element-wise) multiplication support (only square)
# dot product No

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [40]:
np.dot(matri_3_3, matri_3_3.T)
# scalar multiplication support
# matrix (element-wise) multiplication No
# dot product support

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [44]:
print(np.matmul(matri_3_3, matri_3_3.T))
print(matri_3_3 @ matri_3_3.T)
# scalar multiplication No
# matrix (element-wise) multiplication No
# dot product support 

[[ 5 11 17]
 [11 25 39]
 [17 39 61]]
[[ 5 11 17]
 [11 25 39]
 [17 39 61]]


#### Verification: $I_mA = AI_n$

In [49]:
matr_ver = np.arange(1,7).reshape(2,3)
i_ver_front = np.eye(2, dtype=int)
i_ver_end = np.eye(3,dtype=int)
print(matr_ver)
print(i_ver_front)
print(i_ver_front @ matr_ver)
print(np.dot(i_ver_front,matr_ver))

print(matr_ver @ i_ver_end)

# how to use slice in matrix
print(matr_ver[:2,:2])

[[1 2 3]
 [4 5 6]]
[[1 0]
 [0 1]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


#### Inverse of matrix

In [61]:
a = np.arange(1,5).reshape(2,2)
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)
print(np.dot(a,a_inv))


[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
